server:
  port: 8087
spring:
  application:
    name: DEMO-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

security:
  restApi:
    authenticatedInfoUrl: http://localhost:5555/api/auth/authinfo

eureka:
  instance:
    prefer-ip-address: true
  client:
    # Pull down a local copy of the registry
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/